// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228160400_AddedTables")]
    partial class AddedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Property<int>("house_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("house_admin_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("house_id");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Property<int>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("transaction_category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("transaction_description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("transaction_for_house_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("transaction_from_user_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("transaction_is_repetable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("transaction_value")
                        .HasColumnType("INTEGER");

                    b.HasKey("transaction_id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_house_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
