// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228161952_AddedForeignKeys")]
    partial class AddedForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Property<int>("house_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_admin_id");

                    b.HasKey("house_id");

                    b.HasIndex("DBUserId")
                        .IsUnique();

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Property<int>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBHouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_for_house_id");

                    b.Property<int>("DBUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_from_user_id");

                    b.Property<string>("transaction_category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("transaction_description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("transaction_is_repetable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("transaction_value")
                        .HasColumnType("TEXT");

                    b.HasKey("transaction_id");

                    b.HasIndex("DBHouseId");

                    b.HasIndex("DBUserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBHouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_house_id");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "DBUser")
                        .WithOne("DBHouse")
                        .HasForeignKey("HomeBudgetManager.Core.DBTables.DBHouse", "DBUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBUser");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "DBHouse")
                        .WithMany()
                        .HasForeignKey("DBHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "DBUser")
                        .WithMany()
                        .HasForeignKey("DBUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBHouse");

                    b.Navigation("DBUser");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Navigation("DBHouse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
