// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105160839_fixedDBHouseIdForTransactionCanBeNullable")]
    partial class fixedDBHouseIdForTransactionCanBeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCategory", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Property<int>("house_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_id");

                    b.Property<int>("house_admin_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_admin_id");

                    b.Property<string>("house_description")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_description");

                    b.Property<string>("house_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_name");

                    b.HasKey("house_id");

                    b.HasIndex("house_admin_id");

                    b.HasIndex("house_name")
                        .IsUnique();

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Property<int>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBHouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_for_house_id");

                    b.Property<int>("DBUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_from_user_id");

                    b.Property<string>("transaction_category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("transaction_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("transaction_description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("transaction_is_repetable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("transaction_value")
                        .HasColumnType("TEXT");

                    b.HasKey("transaction_id");

                    b.HasIndex("DBHouseId");

                    b.HasIndex("DBUserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<int?>("user_house_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_house_id");

                    b.Property<string>("user_login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_login");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_password");

                    b.Property<int>("user_role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.HasIndex("user_house_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "admin")
                        .WithMany()
                        .HasForeignKey("house_admin_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "DBHouse")
                        .WithMany()
                        .HasForeignKey("DBHouseId");

                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "DBUser")
                        .WithMany()
                        .HasForeignKey("DBUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBHouse");

                    b.Navigation("DBUser");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "house")
                        .WithMany("Members")
                        .HasForeignKey("user_house_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("house");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
