// <auto-generated />
using System;
using HomeBudgetManager.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeBudgetManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106124610_fixedAdminId")]
    partial class fixedAdminId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBCategory", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_description");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_id");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("house_description");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("house_name");

                    b.Property<int>("house_admin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("house_admin");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description_category");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_description");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_for_house_id");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_is_repeatable");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_from_user_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_email");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_house_id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_password");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role");

                    b.Property<int?>("user_house_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseId");

                    b.ToTable("users", t =>
                        {
                            t.Property("user_house_id")
                                .HasColumnName("user_house_id1");
                        });
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBUser", "Admin")
                        .WithMany()
                        .HasForeignKey("house_admin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBTransaction", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "House")
                        .WithMany()
                        .HasForeignKey("HouseId");

                    b.Navigation("House");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBUser", b =>
                {
                    b.HasOne("HomeBudgetManager.Core.DBTables.DBHouse", "House")
                        .WithMany("Members")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("House");
                });

            modelBuilder.Entity("HomeBudgetManager.Core.DBTables.DBHouse", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
